# -*- coding: utf-8 -*-
"""Ej6_Sec2.3.6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqywVxjGBurckYn0iQpee5Of26nbeZtM
"""

import sympy
from sympy import *

#Dimensión del espacio
n = 4

#Base
B = zeros(1,n+1)
t = symbols("t")
for i in range (n+1):
    B[0,i] = t**i
B

"""Ortogonalización de los vectores utilizando la definición de producto interno

$\langle f | g \rangle=\int_{-1}^1 f(x)g(x)\sqrt{1-x^2}dx$
"""

#Base ortogonal
B_ = B

#Ortogonalización de los vectores
#Con los índices 'i' iteramos sobre los nuevos vectores ortogonales,
#Con los índices 'j' construímos cada una de las restas necesarias
#en el proceso de ortogonalización para cada vector dado por 'i'

for i in range (1,n+1):
    for j in range (i,0,-1):
        B_[0,i] -= integrate(B_[0,i]*B_[0,j-1]*sqrt(1-t**2),(t,-1,1))*B_[0,j-1] / integrate(B_[0,j-1]**2*sqrt(1-t**2),(t,-1,1))

B_

