# -*- coding: utf-8 -*-
"""Ej3_sec2_4_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlIDb6KkKhw0vl45aS9n-DgNiB2xA7vh

Espacio vectorial: funciones reales infinitamente diferenciables en [-1,1]

El conjunto de monomios {$1,x^2,x^3,...$} es linealmente independiente
"""

import sympy
from sympy import *

#Creamos el conjunto
n = 10
c = zeros(1,n)
x = symbols('x')
for i in range(n):
  c[0,i] = x**i
c

"""###a) Demostrar que el conjunto no es ortogonal bajo el producto interno

$\int_{-1}^1 f(x)g(x)dx$
"""

#Basta con probar que haya dos que no sean ortogonales
integrate(c[0,1]*c[0,3],(x,-1,1))

"""###b) Ortogonalización para los primeros 10"""

c_ = c

#utilizaré el mismo método que en el ejercicio 6 de la sección 2.3.6:
#Con los índices 'i' iteramos sobre los nuevos vectores ortogonales,
#Con los índices 'j' construímos cada una de las restas necesarias
#en el proceso de ortogonalización para cada vector dado por 'i'

for i in range (1,n):
    for j in range (i,0,-1):
        c_[0,i] -= integrate(c_[0,i]*c[0,j-1],(x,-1,1))*c_[0,j-1] / integrate(c_[0,j-1]**2,(x,-1,1))

c_

"""###c) Modificando la definición de producto interno a

$\int_{-1}^1 f(x)g(x)\sqrt{1-x^2}dx$
"""

c_ = c

#Ortogonalizando de la misma manera que en el punto b:

for i in range (1,n):
    for j in range (i,0,-1):
        c_[0,i] -= integrate(c_[0,i]*c[0,j-1]*sqrt(1-x**2),(x,-1,1))*c_[0,j-1] / integrate(c_[0,j-1]**2*sqrt(1-x**2),(x,-1,1))
c_

